POST http://127.0.0.1:8888/api/account/login/
content-type: application/json

{
    "email": "benpr438@student.liu.se",
    "password": ""
}

### 

POST  http://127.0.0.1:8888/api/account/
content-type: application/json

{
"univID": "benpr438",
"password": "nouppercase",
"firstName": "toto",
"lastName": "titi",
"promo": 2024,
"email": "benpr438@student.liu.se"
}

###

POST http://127.0.0.1:8888/api/account/login/
content-type: application/json

{
    "password": "tooFaitdukayak2!"
}